### ISSUE TITLE
 Fatal error: Declaration of CMB2_Type_File::render() must be compatible

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/kiwi-social-share-lite#2]
https://wordpress.org/support/topic/fatal-error-declaration-of-cmb2_type_filerender-must-be-compatible/

**Comment by giucu91** [comment]
Fixed https://github.com/MachoThemes/kiwi-social-share-lite/blob/master/includes/lib/cmb2/includes/types/CMB2_Type_File.php#L21
